import Head from "next/head";
// import BoardPage from "./board";
// import HeaderPage from "../src/layout/header.jsx";

export default function Home() {
  return (
    <>
      <Head>
        <title>Drinking</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          margin: "0 auto",
          width: "100%",
          padding: "0",
        }}
      ></div>
    </>
  );
}
